// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efdfzjflqhibikbylrhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZGZ6amZscWhpYmlrYnlscmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzE3NzksImV4cCI6MjA3MzcwNzc3OX0.b56NCXsNEl3-teyipaGcy9cEdWmZHI8ODf9991rrk5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});